# Generated by Django 5.0.2 on 2024-02-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_from', models.CharField(max_length=100)),
                ('user_to', models.CharField(max_length=100)),
                ('km', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
